### ISSUE TITLE
Code for non Node.js version

### ISSUE THREAD

**Issue by Iqwertz** [svgdotjs/svg.topath.js#13]
Currently the only way to use this Extension is with npm.
The problem is I dont want to use node.js for my project.
Is there a way to use this extension without node.js (Only vanilla js with svg.js library)?
Or am I comletly missunderstanding npm and node.js (I am really new to these topics)?

**Comment by derhuerst** [comment]
I assume you want to use `svg.topath.js` in the browser instead?

There are two ways for this:

- In general, most npm packages that don't call Node-specific APIs (e.g. file system), can be transformed in a way so that they work in the browser; What happens: A special program called "bundler" will compile a list of all necessary files of the npm package *and its dependencies*, and bundle them together. Use [`browserify`](http://browserify.org) ([guide](https://github.com/substack/browserify-handbook)) for an older but simple tool, or [webpack](https://webpack.js.org) for a more complex but powerful one.
- The `@svgdotjs/svg.topath.js` npm package has an additional method: It contains a `dist` directory with pre-bundled versions of the code, which you can just add via `<script>`. For development purposes you can also use [unpkg](https://unpkg.com) to hotlink this pre-bundled code: `https://unpkg.com/@svgdotjs/svg.topath.js@2.0.3/dist/svg.topath.js`.

**Comment by Fuzzyma** [comment]
svg.js is a clientside library. We always have bundles that can go directly into the script tag i your html code. You can find those bundles on npm or in the dist folder of the repository. If there is no dist folder, you can haev a look at releases and download it there

**Comment by Iqwertz** [comment]
Thank you! Didn't know that! Found it in the releases
